doFull: doFull.c
	gcc -g -O2 -Wall -lpopt doFull.c -o doFull
	sudo chown kharispe doFull
	sudo chmod u+s doFull

doDig: doDig.c
	gcc -O2 -Wall -lpopt doDig.c -o doDig
	sudo chown kharispe doDig
	sudo chmod u+s doDig

doPing: doPing.c
	gcc -O2 -Wall -lpopt doPing.c -o doPing
	sudo chown kharispe doPing
	sudo chmod u+s doPing

doTrace: doTrace.c
	gcc -O2 -Wall -lpopt doTrace.c -o doTrace
	sudo chown kharispe doTrace
	sudo chmod u+s doTrace
